services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: psychology_app
    restart: unless-stopped
    ports:
      - "8002:80"
    environment:
      APP_ENV: prod
      APP_SECRET: ${APP_SECRET}
      DATABASE_URL: mysql://psychology:${MYSQL_PASSWORD}@database:3306/psychology?serverVersion=11.2.0-MariaDB
      JWT_SECRET_KEY: /var/www/html/config/jwt/private.pem
      JWT_PUBLIC_KEY: /var/www/html/config/jwt/public.pem
      JWT_PASSPHRASE: ${JWT_PASSPHRASE}
    depends_on:
      database:
        condition: service_healthy
    volumes:
      - ./var/log:/var/www/html/var/log
      - ./config/jwt:/var/www/html/config/jwt:ro

  database:
    image: mariadb:11.2
    container_name: psychology_db
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: psychology
      MYSQL_USER: psychology
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - database_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s

volumes:
  database_data:
